### ISSUE TITLE
Don't use Outlook.com SVG on outlook.office.com / outlook.office365.com

### ISSUE THREAD

**Issue by KIPdeKIP** [EIGHTFINITE/outlook-com-sleek-tidy#12]
According to a user report the style is wrongly being applied to Office 365.

---

<sup>Reported by a user on the Userstyles website: https://forum.userstyles.org/discussion/56451/make-it-for-outlook-com-only</sup>

**Comment by KIPdeKIP** [comment]
Pushing this back to [Update 9](https://github.com/EIGHTFINITE/outlook-com-sleek-tidy/milestone/7).

**Comment by KIPdeKIP** [comment]
As far as I can tell, everything is working correctly on `office.com` and `office365.com`. I can't reproduce whatever is going wrong.

**Comment by iamCristYe** [comment]
Hi,

I'm sorry I don't check user style regularly.

I just feel like the mail app in Office 365 is not called "Outlook.com" so the SVG should not be used.

And also, it seems that something is wrong with the shadow in Office 365(https://outlook.office.com/owa/ or https://outlook.office365.com/owa/):
![image](https://user-images.githubusercontent.com/12642018/27612190-3c5b28fc-5b4a-11e7-9b66-fd3f6d7b6537.png)
A same theme in Outlook.com(https://outlook.live.com/owa/) is fine:
![image](https://user-images.githubusercontent.com/12642018/27612200-48fab758-5b4a-11e7-9fa2-fa802c434a4f.png)
Thanks!

**Comment by KIPdeKIP** [comment]
I get what you mean now. You're right in saying it's not Outlook.com. That's a leftover from throwing all the rules at Office 365 to start supporting it. The SVG doesn't perfectly match the Office 365 text either. I'll move it to its own section so it only applies to the `outlook.live.com` domain.

As for the shadow, that's the Outlook theme being overwritten by the userstyle. I had a bit of difficulty reproducing that since it corrects itself when you refresh on / visit the change theme page. (I don't use any themes myself so I never left that page with any themes on. Only found it by accident this time.) I'll create another issue to get that fixed.

**Comment by KIPdeKIP** [comment]
I've pushed a fix to the repo. Should be able to roll this along with the rest of [Update 9](https://github.com/EIGHTFINITE/outlook-com-sleek-tidy/milestone/7) out this weekend.

**Comment by iamCristYe** [comment]
Just being curious, is my original text difficult to understand (Because my native language is not English)?

**Comment by KIPdeKIP** [comment]
Your text isn't difficult to understand. Not sure what to call it. I guess it's just worded slightly weird?

Using "CSS code" and "and" made me think both Onedrive and 365 had the same problem of the complete style being applied somewhere it shouldn't be. Went to look at Onedrive and found the problem pretty quick, went to 365 and couldn't find anything because I was looking for the wrong thing.

My native language isn't English either so that didn't help either.

You could've used something along the lines of "SVG logo" instead of "CSS code" to make it work with the "and" or could've split them up saying "The current CSS code applies to OneDrive. There's a logo on Office 365 which is not Outlook.com".

Everything worked out though so you didn't do anything wrong in my book.
